version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_DSN=redis:6379
      - MONGODB_URI=mongodb://mongodb:27017
      - ADMIN_MAIL=karthick.pannerselvam@humetis.in
      - ADMIN_NAME=Kumar
    links:
      - redis
      - mongodb
    depends_on:
      - mongodb
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"